apiVersion: v1
kind: Service
metadata:
  name: resumevalidate-service
spec:
  selector:
    app: resumevalidate
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP  # Change this if you're using a different type of service

