apiVersion: v1
kind: Service
metadata:
  name: mysql-resume-validate-service
spec:
  selector:
    app: mysql-resume-validate
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: LoadBalancer
